updated git publish script to stash and include safety check

diff --git a/bin/git-publish b/bin/git-publish
--- a/bin/git-publish
+++ b/bin/git-publish
@@ -1,83 +1,59 @@
 #!/bin/sh
-#---------------------------------------------------------------------------#
-#--                   publish_to functions                                --#
-#---------------------------------------------------------------------------#
-# TODO: safety check to see if is ancestor: git merge-base --is-ancestor $current_branch $1
+# git publish $from $to
+# from defaults to the current branch
+# to defaults to master
+# only works if from is an ancestor of to
 function publish_to {
-current_branch=$(git branch 2>/dev/null | grep -e '^*' | sed -E 's/^\* (.+)$/\1 /')
+  current_branch=$(git branch 2>/dev/null | grep -e '^*' | sed -E 's/^\* (.+)$/\1 /')
 
-if [ "$current_branch" == "" ]; then
-  echo "Error - You do not appear to be on a branch to publish from, please check with 'git branch'";return;
-fi
-if [ "$1" != "" ]; then
-  publish $current_branch $1
-else
-  #echo "Please enter branch you wish to publish to."
-  #echo " --> For example: publish_to <some_branch_name>"
-  publish $current_branch master
-fi
+  if [ "$current_branch" == "" ]; then
+    echo "Error - You do not appear to be on a branch to publish from, please check with 'git branch'"; return;
+  fi
+  if [ "$1" != "" ]; then
+    publish $current_branch $1
+  else
+    publish $current_branch master
+  fi
 }
+
 function publish {
-from=$1
-to=$2
-if [ "$from" == "" ]; then
-        echo "== Error - Please specify branch to publish from"; return;
-elif [ "$to" == "" ]; then
-        echo "== Error - Please specify branch to publish to"; return;
-fi
-echo "-- 1. Checking out '$to' to latest version..."
-git checkout $to
-git fetch origin
-git rebase -p origin/$to
-echo "-- 2. Switching back to '$from'..."
-git checkout $from
-echo "-- 3. Rebasing '$to' to include '$from' (with -p to preserve )..."
-git rebase -p $to
-echo "-- 4. Switching back to '$to'..."
-git checkout $to
-echo "-- 5. Merging in '$from'..."
-git merge $from
-echo "-- 6. Displaying branch status..."
-git status
-#publish_push_options
-#read -p "OK to push? (Y/n)"
-git push
-echo "== All actions completed..."
-git checkout $from
+  from=$1
+  to=$2
+  `git merge-base --is-ancestor $to $from`
+  if [[ $? != 0 ]]; then
+    echo "$from is not an ancestor of $to. Exiting"; return;
+  fi
+
+  from=$1
+  to=$2
+  if [ "$from" == "" ]; then
+    echo "== Error - Please specify branch to publish from"; return;
+  elif [ "$to" == "" ]; then
+    echo "== Error - Please specify branch to publish to"; return;
+  fi
+  out=$(git stash)
+  echo "-- 1. Checking out '$to' to latest version..."
+  git checkout $to
+  git fetch origin
+  git rebase -p origin/$to
+  echo "-- 2. Switching back to '$from'..."
+  git checkout $from
+  echo "-- 3. Rebasing '$to' to include '$from' (with -p to preserve )..."
+  git rebase -p $to
+  echo "-- 4. Switching back to '$to'..."
+  git checkout $to
+  echo "-- 5. Merging in '$from'..."
+  git merge $from
+  echo "-- 6. Displaying branch status..."
+  git status
+  git push
+  echo "== All actions completed..."
+  git checkout $from
+
+  if [ "$out" != "No local changes to save" ]; then
+    echo "Restoring stashed changes..."
+    git stash pop
+  fi
 }
-function publish_push_options {
-remotes=""
-normal_options=1
-read -a remotes <<< $(git remote)
-remote_count=${#remotes[@]}
-remote="${remotes[0]}"
-printf "\n\n\n\n== Would you like to push? Please select option (or any key to skip):\n"
-echo "1) Push all - (git push)"
-if [ $remote_count -ge 1 ]; then
-for ((i=0; i<$remote_count; i++))
-do
-echo "$((i+($normal_options+1)))) Push '$to' - (git push ${remotes[$i]} $to)"
-done
-fi
-echo "-) Skip"
-read -n1 -s -r -t30 INPUT
-case "$INPUT" in
-"1")
-echo "== Pushing all changes on '$to' (please wait)..."
-sleep 1
-git push;;
-*)
-if [ "$INPUT" \< "$(($normal_options+$remote_count+1))" ]; then
-remote="${remotes[($INPUT-($normal_options+1))]}";
-echo "== $INPUT Pushing all changes on '$to' to remote '$remote' (please wait)...";
-git push $remote $to;
-else
-echo "== Please complete publish with 'git push $remote $to' / 'git push' while in '$to' whenever you're ready" ;
-fi;;
-esac
-}
-#---------------------------------------------------------------------------#
-#--                   end of publish_to functions                         --#
-#---------------------------------------------------------------------------#
-#bootstrap
+
 publish_to "$1" "$2"
